---
sidebar: sidebar 
permalink: reference-prereq-protect-cloud-native-app-data.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, AWS, deploy Oracle plug-in, BlueXP 
summary: Führen Sie die Voraussetzungen aus, bevor Sie Backups erstellen. 
---
= Voraussetzungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten Zugriff auf BlueXP haben, ein BlueXP-Konto erstellt, die Arbeitsumgebung und den Connector erstellt und das SnapCenter-Plug-in für Oracle bereitgestellt haben.



== Zugriff auf BlueXP

Sollten Sie https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["Melden Sie sich bei BlueXP an"^], Und dann eine https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html["NetApp Konto"^].



== Erstellung von FSX für ONTAP-Arbeitsumgebung

Sie sollten Amazon FSX für ONTAP-Arbeitsumgebungen erstellen, in denen Ihre Datenbanken gehostet werden. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["Erste Schritte mit Amazon FSX für ONTAP"] Und link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Erstellung und Management einer Amazon FSX für ONTAP Arbeitsumgebung"].

Sie können NetApp FSX entweder mit BlueXP oder AWS erstellen. Falls Sie mit AWS erstellt haben, sollten Sie die FSX für ONTAP Systeme in BlueXP entdecken.



== Einen Konnektor erstellen

Ein Account-Administrator muss einen Connector in AWS implementieren, der es BlueXP ermöglicht, Ressourcen und Prozesse in Ihrer Public-Cloud-Umgebung zu managen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["Erstellen eines Connectors in AWS aus BlueXP"].

* Sie sollten denselben Konnektor verwenden, um sowohl FSX-Arbeitsumgebung als auch Oracle-Datenbanken zu verwalten.
* Wenn Sie über die FSX-Arbeitsumgebung und Oracle-Datenbanken in derselben VPC verfügen, können Sie den Connector in derselben VPC implementieren.
* Wenn Sie über die FSX-Arbeitsumgebung und Oracle-Datenbanken in verschiedenen VPCs verfügen:
+
** Wenn auf FSX NAS-Workloads (NFS) konfiguriert sind, können Sie den Connector auf einem der VPCs erstellen.
** Wenn nur SAN-Workloads konfiguriert sind und keine NAS- (NFS-) Workloads verwendet werden sollen, sollte der Connector in der VPC erstellt werden, über den das FSX-System erstellt wird.
+

NOTE: Für die Verwendung von NAS-Workloads (NFS) sollte ein Transit-Gateway zwischen der Oracle Database VPC und FSX VPC vorhanden sein. Auf die NFS-IP-Adresse, die eine unverankerte IP-Adresse ist, kann von einer anderen VPC nur über das Transit-Gateway zugegriffen werden. Wir können nicht auf die Floating IP-Adressen zugreifen, indem wir die VPCs Peering.





Klicken Sie nach dem Erstellen des Connectors auf *Storage* > *Canvas* > *Meine Arbeitsumgebung* > *Arbeitsumgebung hinzufügen* und folgen Sie den Anweisungen, um die Arbeitsumgebung hinzuzufügen. Stellen Sie sicher, dass Konnektivität zwischen dem Connector und den Oracle-Datenbank-Hosts und der FSX-Arbeitsumgebung vorhanden ist. Der Anschluss sollte eine Verbindung zur Cluster-Management-IP-Adresse der FSX-Arbeitsumgebung herstellen können.


IMPORTANT: Klicken Sie nach dem Erstellen des Connectors auf *Connector > Steckverbinder verwalten*; wählen Sie den Namen des Connectors aus, und kopieren Sie die Konnektor-ID.



== Implementieren Sie das SnapCenter Plug-in für Oracle

Sie sollten das SnapCenter Plug-in für Oracle auf jedem der Oracle Datenbank-Hosts bereitstellen. Je nachdem, ob auf dem Oracle-Host die SSH-Schlüsselauthentifizierung aktiviert ist, können Sie eine der Methoden zur Bereitstellung des Plug-ins befolgen.


NOTE: Stellen Sie sicher, DASS JAVA 8 auf jedem der Oracle-Datenbank-Hosts installiert ist und die JAVA_HOME-Variable entsprechend eingestellt ist.



=== Plug-in-Implementierung mit SSH-schlüsselbasierter Authentifizierung

Wenn die SSH-Schlüsselauthentifizierung auf dem Oracle-Host aktiviert ist, können Sie zum Bereitstellen des Plug-ins die folgenden Schritte durchführen. Bevor Sie die Schritte durchführen, stellen Sie sicher, dass die SSH-Verbindung zum Connector aktiviert ist.

. Melden Sie sich bei der Connector-VM als nicht-Root-Benutzer an.
. Ermitteln Sie den Mount-Pfad für die Basis.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Plug-in implementieren
+
`sudo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`

+
** Host_Name ist der Name des Oracle-Hosts, und dies ist ein obligatorischer Parameter.
** ssh_Key_file ist SSH-Schlüssel, der für die Verbindung zum Oracle-Host verwendet wird und dies ist ein obligatorischer Parameter.
** User_Name: Benutzer mit SSH-Berechtigungen auf dem Oracle-Host und dies ist ein optionaler Parameter. Der Standardwert ist ec2-user.
** ssh_Port: SSH-Port auf dem Oracle-Host und dies ist ein optionaler Parameter. Der Standardwert ist 22
** Plugin_Port: Port verwendet vom Plug-in und dies ist ein optionaler Parameter. Der Standardwert ist 8145
** Install_dir: Verzeichnis, in dem das Plug-in bereitgestellt wird und dies ein optionaler Parameter ist. Standardwert ist /opt.




Beispiel: `sudo /var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh --host xxx.xx.x.x  --sshkey /keys/netapp-ssh.ppk`



=== Manuelle Implementierung des Plug-ins

Wenn die SSH-Schlüsselauthentifizierung auf dem Oracle-Host nicht aktiviert ist, sollten Sie die folgenden manuellen Schritte durchführen, um das Plug-in bereitzustellen.

. Melden Sie sich bei der Connector-VM an.
. Laden Sie die SnapCenter Linux Host Plug-in-Binärdatei herunter.
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. Ermitteln Sie den Mount-Pfad für die Basis.
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. Den Binärpfad des heruntergeladenen Plug-ins abrufen.
`sudo ls <base_mount_path> $(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. Kopieren Sie _snapcenter_linux_Host_Plugin_scs.bin_ auf jeden der Oracle-Datenbank-Hosts, entweder mit scp oder anderen alternativen Methoden.
. Führen Sie auf dem Oracle-Datenbank-Host den folgenden Befehl aus, um Berechtigungen für die Binärdatei auszuführen.
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. Implementieren Sie das Oracle Plug-in als Root-Benutzer.
`./snapcenter_linux_host_plugin_scs.bin -i silent`
. Kopieren Sie _Certificate.p12_ von _<base_Mount_PATH>/Client/Certificate/_ Pfad der Connector-VM auf den Plug-in-Host zu _/var/opt/snapcenter/spl/etc/_.
+
.. Navigieren Sie zu _/var/opt/snapcenter/spl/etc_ und führen Sie den keytool-Befehl aus, um das Zertifikat zu importieren.
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
.. SPL neu starten: `systemctl restart spl`



