---
sidebar: sidebar 
permalink: reference-aws-backup-tiers.html 
keywords: aws, amazon, s3, storage classes, archive 
summary: Cloud Backup unterstützt zwei S3-Archiv-Storage-Klassen und die meisten Regionen. 
---
= AWS S3-Archiv-Storage-Klassen und Restore Abrufzeiten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup unterstützt zwei S3-Archiv-Storage-Klassen und die meisten Regionen.



== Unterstützte S3-Archiv-Storage-Klassen für Cloud Backup

Beim ersten Erstellen von Backup-Dateien werden sie im S3 _Standard_ Storage gespeichert. Diese Tier ist für die Speicherung von Daten optimiert, auf die selten zugegriffen wird. Dadurch können Sie jedoch auch sofort auf die Daten zugreifen. Nach 30 Tagen erfolgen die Backups auf die S3 _Standard-infrequent Access_ Storage-Klasse, um Kosten zu sparen.

Wenn in den Quellclustern ONTAP 9.10.1 oder neuer ausgeführt wird, können Sie Backups entweder nach einer bestimmten Anzahl von Tagen (normalerweise über 30 Tage) als Tiering zu _S3 Glacier Deep Archive_ oder _S3 Glacier Deep Archive_ Storage abstufen, um die Kosten weiter zu optimieren. Auf Daten in diesen Tiers kann bei Bedarf nicht sofort zugegriffen werden und verursachen höhere Abrufkosten. Daher müssen Sie bedenken, wie oft Sie Daten aus diesen archivierten Backup-Dateien wiederherstellen müssen. Siehe Abschnitt zu <<Wiederherstellen von Daten aus Archiv-Storage,Wiederherstellen von Daten aus Archiv-Storage>>.

Wenn Sie bei der Aktivierung von Cloud Backup _S3 Glacier_ oder _S3 Glacier Deep Archive_ in Ihrer ersten Backup-Richtlinie auswählen, wird dieser Tier die einzige Archiv-Tier sein, die für zukünftige Backup-Richtlinien für diesen Cluster verfügbar ist. Falls Sie in Ihrer ersten Backup-Richtlinie keinen Archiv-Tier auswählen, ist _S3 Glacier_ die einzige Archivoption für zukünftige Richtlinien.

Wenn Sie Cloud Backup mit dieser Art von Lifecycle-Regel konfigurieren, müssen Sie beim Einrichten des Bucket in Ihrem AWS-Konto keine Lifecycle-Regeln konfigurieren.

https://aws.amazon.com/s3/storage-classes/["Erfahren Sie mehr über S3-Storage-Klassen"^].



== Wiederherstellen von Daten aus Archiv-Storage

Das Speichern älterer Backup-Dateien im Archiv-Storage ist viel kostengünstiger als Standard- oder Standard-IA-Storage. Der Zugriff auf Daten aus einer Backup-Datei im Archiv-Storage für Wiederherstellungsvorgänge dauert viel länger und kostet mehr Geld.

Wie hoch sind die Kosten für die Wiederherstellung von Daten aus Amazon S3 Glacier und Amazon S3 Glacier Deep Archive?:: Es gibt 3 Wiederherstellungsprioritäten, die beim Abrufen von Daten aus Amazon S3 Glacier und beim Abrufen der Daten aus dem Amazon S3 Glacier Deep Archive zwei Wiederherstellungsprioritäten zur Verfügung stehen. S3 Glacier Deep Archive kostet weniger als S3 Glacier:
+
--
[cols="25,25,25,25"]
|===
| Archivebene 3+| Priorität Und Kosten Wiederherstellen 


|  | *Hoch* | *Standard* | *Niedrig* 


| *S3-Gletscher* | Schnellster Abruf, höchste Kosten | Langsameres Abrufen, geringere Kosten | Langsamster Abruf, niedrigste Kosten 


| *S3 Glacier Deep Archive* |  | Schnelleres Abrufen, höhere Kosten | Langsameres Abrufen, geringste Kosten 
|===
Jede Methode hat eine andere Abrufgebühr pro GB und eine andere Gebühr pro Anfrage. Detaillierte Informationen zu den S3-Glacier-Preisen nach AWS Region finden Sie im https://aws.amazon.com/s3/pricing/["Preisseite von Amazon S3"^].

--
Wie lange dauert es, meine in Amazon S3 Glacier archivierten Objekte wiederherzustellen?:: Es gibt zwei Teile, aus denen sich die gesamte Wiederherstellungszeit ergibt:
+
--
* *Retrieval Time*: Der Zeitpunkt, um die Sicherungsdatei aus dem Archiv abzurufen und in den Standard-Speicher zu legen. Dies wird manchmal als die "Rehydrierung" Zeit bezeichnet. Die Abrufzeit ist je nach gewählter Wiederherstellungspriorität unterschiedlich.
+
[cols="25,20,20,20"]
|===
| Archivebene 3+| Stellen Sie Die Priorität Und Den Abruf Wieder Her 


|  | *Hoch* | *Standard* | *Niedrig* 


| *S3-Gletscher* | 3-5 Minuten | 3-5 Stunden | 5-12 Stunden 


| *S3 Glacier Deep Archive* |  | 12 Stunden | 48 Stunden 
|===
* *Restore Time*: Der Zeitpunkt, um die Daten aus der Sicherungsdatei im Standard-Speicher wiederherzustellen. Dieser Vorgang unterscheidet sich nicht von dem typischen Restore-Vorgang direkt vom Standard-Storage, wenn keine Archivebene verwendet wird.


Weitere Informationen zu den Abruffoptionen für Amazon S3 Glacier und S3 Glacier Deep Archive finden Sie unter https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["Die Amazon FAQ zu diesen Speicherklassen"^].

--

