---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: Erstellung der Azure NetApp Files-Arbeitsumgebung und des Connectors 
---
= Konfigurieren Sie Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten die Azure NetApp Files-Arbeitsumgebung und den Connector erstellen.



== Azure NetApp Files Arbeitsumgebung erstellen

Sie sollten Azure NetApp Files (ANF)-Arbeitsumgebungen erstellen, in denen Ihre Datenbanken gehostet werden. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Weitere Informationen zu Azure NetApp Files"] Und link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Schaffung einer Azure NetApp Files-Arbeitsumgebung"].



== Einen Konnektor erstellen

Ein Account-Administrator muss einen Connector in ANF implementieren, der es BlueXP ermöglicht, Ressourcen und Prozesse in Ihrer Public-Cloud-Umgebung zu managen.


NOTE: Sie können die neue Connector_id nicht von der UI aktualisieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Erstellen Sie einen Connector in Azure von BlueXP"].
