---
sidebar: sidebar 
permalink: task-create-policies-vms.html 
keywords: create policy, protection policies, predefined policies, custom policies 
summary: Erstellen einer Richtlinie zum Backup von Virtual Machines 
---
= Erstellen einer Richtlinie zum Backup von Virtual Machines
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine Richtlinie erstellen oder eine der folgenden vordefinierten Richtlinien verwenden, die in BlueXP verfügbar sind.

|===
| Name Der Richtlinie | Etikett | Aufbewahrungswert 


 a| 
1 Jahr tägliche LTR
 a| 
Täglich
 a| 
366



 a| 
5 Jahre tägliche LTR
 a| 
Täglich
 a| 
1830



 a| 
7 Jahre wöchentlicher LTR
 a| 
Wöchentlich
 a| 
370



 a| 
10 Jahre Monatliche LTR
 a| 
Monatlich
 a| 
120

|===
Sie sollten Richtlinien erstellen, wenn Sie die vordefinierten Richtlinien nicht bearbeiten möchten.

.Schritte
. Wählen Sie auf der Seite Virtuelle Maschinen aus der Dropdown-Liste Einstellungen die Option *Richtlinien* aus.
. Klicken Sie auf *Create Policy*.
. Geben Sie im Abschnitt Richtliniendetails den Richtliniennamen an.
. Wählen Sie im Abschnitt Aufbewahrung einen Aufbewahrungstyp aus und geben Sie die Anzahl der zu behaltenden Backups an.
. Wählen Sie Primary oder Secondary als Backup-Speicherquelle aus.
. (Optional) Wenn Sie Backups nach einer bestimmten Anzahl von Tagen zur Kostenoptimierung vom Objektspeicher in den Archivspeicher verschieben möchten, aktivieren Sie das Kontrollkästchen *Tiering Backups in Archival* und geben Sie die Anzahl der Tage ein, nach denen das Backup archiviert werden soll.
+
Sie können Backups nur dann von einem Objektspeicher in einen Archiv-Storage verschieben, wenn Sie ONTAP 9.10.1 oder höher und Amazon Web Services oder Azure als Cloud-Provider verwenden. Sie sollten die Zugriffsebene für den Archiv für jeden Cloud-Provider konfigurieren.

. Klicken Sie Auf *Erstellen*.
+
Sie können die angepassten Richtlinien bearbeiten, kopieren und löschen.

+

NOTE: Eine Richtlinie, die einer virtuellen Maschine zugeordnet ist, kann nicht bearbeitet oder gelöscht werden.


