---
sidebar: sidebar 
permalink: task-create-policies-apps.html 
keywords: policy, create, pre-canned polices, custom policies, protection policies 
summary: Verwenden Sie entweder die vordefinierten Richtlinien oder erstellen Sie Ihre eigenen Richtlinien zum Schutz der Anwendung. 
---
= Erstellen einer Richtlinie für das Backup von Applikationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können entweder eine der vordefinierten Richtlinien verwenden oder eine individuelle Richtlinie für das Backup der Applikationsdaten in der Cloud erstellen. Sie können Richtlinien erstellen, wenn Sie die vordefinierten Richtlinien nicht bearbeiten möchten.

Die vordefinierten Richtlinien sind:

|===
| Name Der Richtlinie | Etikett | Aufbewahrungswert 


 a| 
1 Jahr tägliche LTR
 a| 
Täglich
 a| 
366



 a| 
5 Jahre tägliche LTR
 a| 
Täglich
 a| 
1830



 a| 
7 Jahre wöchentlicher LTR
 a| 
Wöchentlich
 a| 
370



 a| 
10 Jahre Monatliche LTR
 a| 
Monatlich
 a| 
120

|===
*Schritte*

. Klicken Sie in BlueXP UI auf *Schutz* > *Sicherung und Wiederherstellung* > *Anwendungen*.
. Klicken Sie im Dropdown-Menü Einstellungen auf *Richtlinien* > *Richtlinien erstellen*.
. Geben Sie im Abschnitt Richtliniendetails den Richtliniennamen an.
. Wählen Sie im Abschnitt Aufbewahrung einen Aufbewahrungstyp aus und geben Sie die Anzahl der zu behaltenden Backups an.
. Wählen Sie Primary oder Secondary als Backup-Speicherquelle aus.
. (Optional) Wenn Sie Backups nach einer bestimmten Anzahl von Tagen zur Kostenoptimierung vom Objektspeicher in den Archivspeicher verschieben möchten, aktivieren Sie das Kontrollkästchen *Tiering Backups in Archive*.
+
Sie können Backups nur dann von einem Objektspeicher in einen Archiv-Storage verschieben, wenn Sie ONTAP 9.10.1 oder höher und Amazon Web Services oder Azure als Cloud-Provider verwenden. Sie sollten die Zugriffsebene für den Archiv für jeden Cloud-Provider konfigurieren.

. Klicken Sie Auf *Erstellen*.
+
Sie können die angepassten Richtlinien bearbeiten, kopieren und löschen.

+

NOTE: Eine Richtlinie, die einer Anwendung zugeordnet ist, kann nicht bearbeitet oder gelöscht werden.


